env:
  browser: true
  es2021: true
extends:
  - airbnb
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  import/no-unresolved:
  - error
  - ignore:
    - react-native
    - '@expo/vector-icons'
    - expo-constants
  import/extensions:
  - "error"
  - "never"
  - json: "always"
  react/jsx-filename-extension:
  - error
  - extensions:
    - ".ts"
    - ".jsx"
    - ".tsx"
    - ".json"
  no-use-before-define:
  - off
  react/display-name:
  - off
  react/require-default-props: "off"
  "@typescript-eslint/no-explicit-any": "off"
settings:
  import/resolver:
    node:
      extensions:
      - ".js"
      - ".jsx"
      - ".json"
      - ".ts"
      - ".tsx"